DROP TABLE IF EXISTS EVM.GAS_METADATA;

CREATE TABLE IF NOT EXISTS EVM.GAS_METADATA(
    GAS_ID INTEGER NOT NULL,
    CONTRACT_DECIMALS CHAR(2) NOT NULL,
    CONTRACT_NAME CHAR(30) NOT NULL,
    CONTRAT_TICKER CHAR(5) NOT NULL,
    CONTRACT_ADDRESS CHAR(42) NOT NULL,
    LOGO_URL VARCHAR(100) NULL
);

