DROP TABLE IF EXISTS EVM.TRANSACTIONS;

CREATE TABLE IF NOT EXISTS EVM.TRANSACTIONS(
    BLOCKCHAIN VARCHAR(30) NOT NULL,
    BLOCK_TIMESTAMP TIMESTAMP NOT NULL,
    BLOCK_HEIGHT CHAR(10) NOT NULL,
    BLOCK_HASH CHAR(66) NOT NULL,
    TX_HASH CHAR(66) NOT NULL,
    TX_OFFSET INTEGER NOT NULL,
    SUCCESSFUL BOOLEAN NOT NULL,
    MINER_ADDRESS CHAR(42) NOT NULL,
    FROM_ADDRESS CHAR(42) NOT NULL,
    TO_ADDRESS CHAR(42) NOT NULL,
    TX_VALUE VARCHAR(30) NOT NULL,
    TX_VALUE_QUOTE DECIMAL(7,2),
    PRETTY_VALUE_QUOTE CHAR(10),
    GAS_ID INTEGER NOT NULL,
    GAS_OFFERED INTEGER NOT NULL,
    GAS_SPENT INTEGER NOT NULL,
    GAS_PRICE VARCHAR(30),
    FEES_PAID VARCHAR(30) NOT NULL,
    GAS_QUOTE DECIMAL(9,4),
    PRETTY_GAS_QUOTE CHAR(10),
    GAS_QUOTE_RATE DECIMAL(7,2),
    EXPLORER_URL VARCHAR(150) NOT NULL
);