DROP TABLE IF EXISTS EVM.LOGS;

CREATE TABLE IF NOT EXISTS EVM.LOGS(
    TX_OFFSET INTEGER NOT NULL,
    LOG_OFFSET INTEGER NOT NULL,
    TX_HASH CHAR(66) NOT NULL,
    TOKEN_ADDRESS CHAR(42) NOT NULL, 
    LOGS_FUNCTION_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_LOGS PRIMARY KEY (TX_OFFSET,LOG_OFFSET,TX_HASH)
);