DROP TABLE IF EXISTS EVM.PARAMS_ADDRESS;

CREATE TABLE IF NOT EXISTS EVM.PARAMS_ADDRESS(
    PARAM_ID INTEGER NOT NULL,
    TX_OFFSET INTEGER NOT NULL,
    LOG_OFFSET INTEGER NOT NULL,
    TX_HASH CHAR(66) NOT NULL,
    PARAM_NAME VARCHAR(30) NOT NULL,
    PARAM_TYPE VARCHAR(10) NOT NULL,
    INDEXED BOOLEAN NOT NULL,
    VALUE VARCHAR(150) NOT NULL,
    CONSTRAINT PK_PARAM PRIMARY KEY (PARAM_ID)
);