DROP TABLE IF EXISTS BINANCE.TRANSACTIONS;

CREATE TABLE IF NOT EXISTS BINANCE.TRANSACTIONS(
    ORDER_ID CHAR(19) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    FROM_ASSET CHAR(6) NOT NULL,
    FROM_QUANTITY DECIMAL(7,3) NOT NULL,
    FROM_PRICE DECIMAL(10,3) NOT NULL,
    TO_ASSET CHAR(6) NOT NULL,
    TO_QUANTITY DECIMAL(7,3) NOT NULL,
    TO_PRICE DECIMAL(10,3) NOT NULL,
    TRANSACTION_FEE DECIMAL(10,9),
    FEE_ASSET CHAR(6)
);
